# Generated by Django 3.2.4 on 2021-06-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0013_auto_20210620_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Delivery Location',
                'verbose_name_plural': 'Delivery Locations',
            },
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_delivery', models.CharField(choices=[('Free', 'Free'), ('Flat', 'Flat')], default='Flat', max_length=50)),
                ('delivery_target_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverable_location', to='delivery.deliverylocation')),
            ],
            options={
                'verbose_name': 'Type of Delivery',
                'verbose_name_plural': 'Type of  Deliveries',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delivered', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery', to='order.order')),
                ('order_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_type', to='delivery.deliverytype')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
