# Generated by Django 3.2.4 on 2021-06-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delete_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytype',
            name='delivery_target_amount',
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='delivery_target_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
