# Generated by Django 3.2.4 on 2021-06-25 04:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20210623_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverylocation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverytype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
