# Generated by Django 3.2.7 on 2021-09-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='privacy_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='refund_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='terms_condition',
            field=models.TextField(blank=True),
        ),
    ]
