# Generated by Django 3.2.2 on 2021-06-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_alter_coupon_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount',
        ),
    ]
