# Generated by Django 3.2.4 on 2021-06-26 01:42

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('product', '0009_auto_20210614_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_status',
            field=models.CharField(choices=[('gm', 'gm'), ('Kg', 'Kg'), ('ml', 'ml'), ('L', 'L')], default='Kg', max_length=20),
        ),
    ]
