# Generated by Django 3.2.4 on 2021-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210706_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
