# Generated by Django 3.2.4 on 2021-07-07 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210707_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
