# Generated by Django 3.2.4 on 2021-07-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20210707_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.FloatField(default=0.0),
        ),
    ]
