# Generated by Django 3.2.4 on 2021-07-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_status',
            field=models.CharField(choices=[('gm', 'gm'), ('Kg', 'Kg'), ('ml', 'ml'), ('Litre', 'Litre')], default='Kg', max_length=20),
        ),
    ]
