# Generated by Django 3.2.6 on 2021-08-14 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
