# Generated by Django 3.2.7 on 2021-09-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_product_is_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
