# Generated by Django 3.2.4 on 2021-06-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_paymenttype_merchant_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttype',
            name='merchant_status',
            field=models.CharField(choices=[('Agent', 'Agent'), ('Personal', 'Personal')], default='Agent', max_length=50),
        ),
    ]
