# Generated by Django 3.2.4 on 2021-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymenttype_merchant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
