# Generated by Django 3.2.4 on 2021-07-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210511_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='device',
        ),
    ]
