# Generated by Django 3.2.4 on 2021-06-20 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210602_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'DeliveryLocation',
                'verbose_name_plural': 'DeliveryLocations',
            },
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliverys'},
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='charge',
            new_name='target_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='coupon_discount',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='name',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_type_name',
            field=models.CharField(default='free', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverable_order', to='order.order'),
        ),
    ]
