# Generated by Django 3.2.4 on 2021-06-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210620_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_type', to='order.delivery'),
        ),
    ]
