# Generated by Django 3.2.4 on 2021-06-20 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_deliverylocation_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocation',
            name='delivery',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryLocation',
        ),
    ]
