# Generated by Django 3.2.4 on 2021-06-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_delivery_deliverylocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='target_amount',
            new_name='delivery_charge',
        ),
    ]
