# Generated by Django 3.2.4 on 2021-06-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_target_amount_delivery_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverable_location', to='order.deliverylocation'),
        ),
    ]
