# Generated by Django 3.2.4 on 2021-06-20 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_delivery_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_charge',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='location',
        ),
        migrations.RemoveField(
            model_name='deliverylocation',
            name='target_amount',
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_type', to='order.order'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_delivery', to='order.order'),
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('Free', 'Free'), ('Flat', 'Flat')], default='Flat', max_length=50)),
                ('delivery_target_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverable_location', to='order.deliverylocation')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
