# Generated by Django 3.2.4 on 2021-06-20 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20210620_0246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverylocation',
            options={'verbose_name': 'Delivery Location', 'verbose_name_plural': 'Delivery Locations'},
        ),
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'verbose_name': 'Type of Delivery', 'verbose_name_plural': 'Type of  Deliveries'},
        ),
        migrations.AlterField(
            model_name='delivery',
            name='order_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_type', to='order.deliverytype'),
        ),
    ]
