# Generated by Django 3.2.4 on 2021-06-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20210620_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverytype',
            old_name='delivery_status',
            new_name='type_of_delivery',
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
