# Generated by Django 3.2.4 on 2021-06-20 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20210620_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverytype',
            name='location',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryLocation',
        ),
        migrations.DeleteModel(
            name='DeliveryType',
        ),
    ]
