# Generated by Django 3.2.4 on 2021-07-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
