# Generated by Django 3.2.7 on 2021-09-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_order_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Delivered', 'Delivered'), ('Refunded', 'Refunded')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(default='123', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted')], default='Requested', max_length=30),
            preserve_default=False,
        ),
    ]
