# Generated by Django 3.2.7 on 2021-09-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20210906_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Accepted', 'Accepted')], max_length=30),
        ),
    ]
